version: '3.4'

services:
    sofar-reader:
        image: sofar-reader
        container_name: sofar-reader
        restart: unless-stopped
#        volumes:
#            - ./src:/usr/src/app
        env_file:
            - .env
        build:
            context: ./sofar-reader
            dockerfile: ./Dockerfile
    sofardb:
        image: timescale/timescaledb:2.7.0-pg14
        container_name: sofardb
        restart: unless-stopped
        ports:
            - ${DBPORT:?".env file not set"}:5432
        volumes:
            - ./sofardb/data:/var/lib/postgresql/data
        env_file:
            - .env
    sofarmq:
        image: rabbitmq:3.10.1-management-alpine
        container_name: sofarmq
        restart: unless-stopped
        hostname: rabbitmq
        ports:
        - 5672:5672
        - 15672:15672
        volumes:
        - ./sofarmq/data/:/var/lib/rabbitmq/
        - ./sofarmq/log/:/var/log/rabbitmq
