version: '3.4'

services:
    sofar:
        image: sofar
        container_name: sofar
        restart: unless-stopped
#        volumes:
#            - ./src:/usr/src/app
        env_file:
            - .env
        build:
            context: ./sofar
            dockerfile: ./Dockerfile
    sofardb:
        image: influxdb:2.2.0
        container_name: sofardb
        restart: unless-stopped
        ports:
            - 8086:8086
        volumes:
            - ./sofardb/data:/var/lib/influxdb
            - ./sofardb/config:/etc/influxdb2
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
        env_file:
            - .env
    rabbitmq:
        image: rabbitmq:3.10.1-management-alpine
        container_name: rabbitmq
        restart: unless-stopped
        hostname: rabbitmq
        ports:
        - 5672:5672
        - 15672:15672
        volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
    telegraf:
        image: telegraf:1.22.4-alpine
        container_name: telegraf
        restart: unless-stopped
        volumes:
        - ./rabbitmg-to-influxdb.telegraf.conf:/etc/telegraf/telegraf.conf
        env_file:
            - .env
#        ports: 8094:8094
