version: '3.4'

services:
    sofar:
        image: sofar
        container_name: sofar
        restart: unless-stopped
#        volumes:
#            - ./src:/usr/src/app
        build:
            context: ./sofar
            dockerfile: ./Dockerfile
    influxdb:
        image: influxdb:2.2.0
        container_name: influxdb
        restart: unless-stopped
        ports:
            - 8086:8086
        volumes:
            - $PWD/influxdb:/var/lib/influxdb 
    rabbitmq:
        image: rabbitmq:3.10.1-management-alpine
        container_name: rabbitmq
        restart: unless-stopped
        hostname: rabbitmq
        ports:
        - 5672:5672
        - 15672:15672
        volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
